import {
  BadgeCheck,
  BarChart3,
  Bell,
  Bookmark,
  Boxes,
  Bug,
  CalendarCheck,
  ClipboardList,
  Cloud,
  FileText,
  FlaskConical,
  Landmark,
  LayoutDashboard,
  Leaf,
  ListChecks,
  MapPin,
  MessageSquare,
  Package,
  PackagePlus,
  Receipt,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sprout,
  Star,
  Store,
  TrendingUp,
  Users,
  UserCircle,
  Activity,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";
import type { Role } from "./data";

export interface NavItem {
  label: string;
  path: string;
  icon: LucideIcon;
  group?: string;
}

export const NAV: Record<Role, NavItem[]> = {
  farmer: [
    { label: "Dashboard", path: "farmer/dashboard", icon: LayoutDashboard },
    { label: "Crop Help", path: "farmer/crop-help", icon: HelpCircle },
    { label: "My Questions", path: "farmer/questions", icon: ClipboardList },
    { label: "Chat with Expert", path: "farmer/chat", icon: MessageSquare },
    { label: "My Crops", path: "farmer/crops", icon: Sprout },
    { label: "Today's Mandi Prices", path: "farmer/mandi-prices", icon: TrendingUp },
    { label: "Weather Forecast", path: "farmer/weather", icon: Cloud },
    { label: "Government Schemes", path: "farmer/schemes", icon: Landmark },
    { label: "Nearby Services", path: "farmer/services", icon: MapPin },
    { label: "Notifications", path: "farmer/notifications", icon: Bell },
    { label: "My Profile", path: "farmer/profile", icon: UserCircle },
    { label: "Settings", path: "farmer/settings", icon: Settings },
  ],
  seller: [
    { label: "Dashboard", path: "seller/dashboard", icon: LayoutDashboard },
    { label: "Add Produce", path: "seller/add-product", icon: PackagePlus },
    { label: "My Listings", path: "seller/listings", icon: ListChecks },
    { label: "Inventory", path: "seller/inventory", icon: Boxes },
    { label: "Orders", path: "seller/orders", icon: Receipt },
    { label: "Buyers", path: "seller/buyers", icon: Users },
    { label: "Buyer Enquiries", path: "seller/enquiries", icon: MessageSquare },
    { label: "Market Prices", path: "seller/market-prices", icon: TrendingUp },
    { label: "Sales Analytics", path: "seller/analytics", icon: BarChart3 },
    { label: "Reviews", path: "seller/reviews", icon: Star },
    { label: "Notifications", path: "seller/notifications", icon: Bell },
    { label: "Seller Profile", path: "seller/profile", icon: UserCircle },
    { label: "Settings", path: "seller/settings", icon: Settings },
  ],
  officer: [
    { label: "Dashboard", path: "officer/dashboard", icon: LayoutDashboard },
    { label: "Farmer Queries", path: "officer/queries", icon: ClipboardList },
    { label: "Pending Queries", path: "officer/pending", icon: CalendarCheck },
    { label: "My Assigned Queries", path: "officer/assigned", icon: ListChecks },
    { label: "Chat with Farmers", path: "officer/chat", icon: MessageSquare },
    { label: "Crops", path: "officer/crops", icon: Sprout },
    { label: "Diseases", path: "officer/diseases", icon: Bug },
    { label: "Pesticides", path: "officer/pesticides", icon: Leaf },
    { label: "Fertilizers", path: "officer/fertilizers", icon: FlaskConical },
    { label: "Knowledge Library", path: "officer/library", icon: FileText },
    { label: "Weather", path: "officer/weather", icon: Cloud },
    { label: "Farmers", path: "officer/farmers", icon: Users },
    { label: "My Certifications", path: "officer/certifications", icon: BadgeCheck },
    { label: "Reports", path: "officer/reports", icon: BarChart3 },
    { label: "Notifications", path: "officer/notifications", icon: Bell },
    { label: "Profile", path: "officer/profile", icon: UserCircle },
    { label: "Settings", path: "officer/settings", icon: Settings },
  ],
  buyer: [
    { label: "Dashboard", path: "buyer/dashboard", icon: LayoutDashboard },
    { label: "Marketplace", path: "buyer/marketplace", icon: ShoppingBag },
    { label: "Market Prices", path: "buyer/market-prices", icon: TrendingUp },
    { label: "My Orders", path: "buyer/orders", icon: Receipt },
    { label: "Saved Products", path: "buyer/saved", icon: Bookmark },
    { label: "Sellers", path: "buyer/sellers", icon: Store },
    { label: "Messages", path: "buyer/messages", icon: MessageSquare },
    { label: "Notifications", path: "buyer/notifications", icon: Bell },
    { label: "Profile", path: "buyer/profile", icon: UserCircle },
    { label: "Settings", path: "buyer/settings", icon: Settings },
  ],

  admin: [
    { label: "Dashboard", path: "admin/dashboard", icon: LayoutDashboard },
    { label: "User Management", path: "admin/users", icon: Users },
    { label: "Farmers", path: "admin/farmers", icon: Sprout, group: "Users" },
    { label: "Sellers", path: "admin/sellers", icon: Store, group: "Users" },
    { label: "Krushi Adhikaris", path: "admin/officers", icon: BadgeCheck, group: "Users" },
    { label: "Buyers", path: "admin/buyers", icon: Store, group: "Users" },
    { label: "Pending Approvals", path: "admin/approvals", icon: ShieldCheck, group: "Users" },
    { label: "Queries", path: "admin/queries", icon: ClipboardList },
    { label: "Produce Listings", path: "admin/products", icon: Package, group: "Marketplace" },
    { label: "Orders", path: "admin/orders", icon: Receipt, group: "Marketplace" },
    { label: "Government Schemes", path: "admin/schemes", icon: Landmark },
    { label: "Agriculture Services", path: "admin/services", icon: MapPin },
    { label: "Content Management", path: "admin/content", icon: FileText },
    { label: "Notifications", path: "admin/notifications", icon: Bell },
    { label: "Reports & Analytics", path: "admin/reports", icon: BarChart3 },
    { label: "System Activity", path: "admin/activity", icon: Activity },
    { label: "Settings", path: "admin/settings", icon: Settings },
  ],
};

export const ROLE_LABEL: Record<Role, string> = {
  farmer: "Farmer",
  seller: "Seller",
  officer: "Krushi Adhikari",
  buyer: "Buyer",
  admin: "Admin",
};

export const MOBILE_NAV: Record<Role, NavItem[]> = {
  farmer: [
    { label: "Home", path: "farmer/dashboard", icon: LayoutDashboard },
    { label: "Crop Help", path: "farmer/crop-help", icon: HelpCircle },
    { label: "Queries", path: "farmer/questions", icon: ClipboardList },
    { label: "Mandi", path: "farmer/mandi-prices", icon: TrendingUp },
    { label: "Alerts", path: "farmer/notifications", icon: Bell },
  ],
  seller: [
    { label: "Home", path: "seller/dashboard", icon: LayoutDashboard },
    { label: "Listings", path: "seller/inventory", icon: Boxes },
    { label: "Orders", path: "seller/orders", icon: Receipt },
    { label: "Prices", path: "seller/market-prices", icon: TrendingUp },
    { label: "Alerts", path: "seller/notifications", icon: Bell },
  ],
  officer: [
    { label: "Home", path: "officer/dashboard", icon: LayoutDashboard },
    { label: "Queries", path: "officer/queries", icon: ClipboardList },
    { label: "Chat", path: "officer/chat", icon: MessageSquare },
    { label: "Reports", path: "officer/reports", icon: BarChart3 },
    { label: "Alerts", path: "officer/notifications", icon: Bell },
  ],
  buyer: [
    { label: "Home", path: "buyer/dashboard", icon: LayoutDashboard },
    { label: "Market", path: "buyer/marketplace", icon: ShoppingBag },
    { label: "Orders", path: "buyer/orders", icon: Receipt },
    { label: "Prices", path: "buyer/market-prices", icon: TrendingUp },
    { label: "Alerts", path: "buyer/notifications", icon: Bell },
  ],

  admin: [
    { label: "Home", path: "admin/dashboard", icon: LayoutDashboard },
    { label: "Users", path: "admin/users", icon: Users },
    { label: "Approvals", path: "admin/approvals", icon: ShieldCheck },
    { label: "Reports", path: "admin/reports", icon: BarChart3 },
    { label: "Alerts", path: "admin/notifications", icon: Bell },
  ],
};

export const SEARCH_INDEX = [
  { label: "PM-KISAN scheme", path: "farmer/schemes", kind: "Scheme", icon: Landmark },
  { label: "Fasal Bima Yojana", path: "farmer/schemes", kind: "Scheme", icon: Landmark },
  { label: "Tomato Grade A listing", path: "buyer/marketplace", kind: "Listing", icon: Package },
  { label: "Onion Nashik Red listing", path: "buyer/marketplace", kind: "Listing", icon: Package },
  { label: "Soybean FAQ listing", path: "buyer/marketplace", kind: "Listing", icon: Package },
  {
    label: "Tomato market price Solapur Mandi",
    path: "buyer/market-prices",
    kind: "Market Price",
    icon: TrendingUp,
  },
  {
    label: "Onion market price Lasalgaon Mandi",
    path: "buyer/market-prices",
    kind: "Market Price",
    icon: TrendingUp,
  },
  { label: "My produce orders", path: "buyer/orders", kind: "Orders", icon: Receipt },
  {
    label: "QRY-2026-1041 Soybean yellowing",
    path: "farmer/questions",
    kind: "Query",
    icon: ClipboardList,
  },
  {
    label: "How to Control Yellow Leaves in Soybean",
    path: "farmer/library",
    kind: "Article",
    icon: FileText,
  },
  { label: "Shree Krushi Seva Kendra", path: "farmer/services", kind: "Service", icon: MapPin },
  { label: "Soil Testing Laboratory", path: "farmer/services", kind: "Service", icon: MapPin },
  { label: "Weather advisory Solapur", path: "farmer/weather", kind: "Weather", icon: Cloud },
  {
    label: "Crop calendar & sowing dates",
    path: "farmer/crops",
    kind: "Crops",
    icon: CalendarCheck,
  },
  { label: "Saved schemes", path: "farmer/schemes", kind: "Saved", icon: Bookmark },
];
